Implements ui.progress if Mercurial doesn't have it
Mercurial in Ubuntu Karmic doesn't have the ui.progress() method, giving the
following exception:

$ hg clone git://github.com/schacon/munger.git
destination directory: munger
importing Hg objects into Git
** unknown exception encountered, details follow
** report bug details to http://mercurial.selenic.com/bts/
** or mercurial@selenic.com
** Mercurial Distributed SCM (version 1.3.1)
** Extensions loaded: rebase, mq, purge, convert, record, hgk, bookmarks, hggit
Traceback (most recent call last):
  File "/usr/bin/hg", line 27, in <module>
    mercurial.dispatch.run()
  File "/usr/lib/pymodules/python2.6/mercurial/dispatch.py", line 16, in run
    sys.exit(dispatch(sys.argv[1:]))
  File "/usr/lib/pymodules/python2.6/mercurial/dispatch.py", line 27, in dispatch
    return _runcatch(u, args)
  File "/usr/lib/pymodules/python2.6/mercurial/dispatch.py", line 43, in _runcatch
    return _dispatch(ui, args)
  File "/usr/lib/pymodules/python2.6/mercurial/dispatch.py", line 449, in _dispatch
    return runcommand(lui, repo, cmd, fullargs, ui, options, d)
  File "/usr/lib/pymodules/python2.6/mercurial/dispatch.py", line 317, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/usr/lib/pymodules/python2.6/mercurial/dispatch.py", line 501, in _runcommand
    return checkargs()
  File "/usr/lib/pymodules/python2.6/mercurial/dispatch.py", line 454, in checkargs
    return cmdfunc()
  File "/usr/lib/pymodules/python2.6/mercurial/dispatch.py", line 448, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
  File "/usr/lib/pymodules/python2.6/mercurial/util.py", line 402, in check
    return func(*args, **kwargs)
  File "/usr/lib/pymodules/python2.6/mercurial/commands.py", line 636, in clone
    update=not opts.get('noupdate'))
  File "/usr/lib/pymodules/python2.6/mercurial/hg.py", line 286, in clone
    dest_repo.clone(src_repo, heads=revs, stream=stream)
  File "/usr/lib/pymodules/python2.6/mercurial/localrepo.py", line 2177, in clone
    return self.pull(remote, heads)
  File "build/bdist.linux-x86_64/egg/hggit/hgrepo.py", line 12, in pull
  File "build/bdist.linux-x86_64/egg/hggit/git_handler.py", line 94, in fetch
  File "build/bdist.linux-x86_64/egg/hggit/git_handler.py", line 114, in export_commits
  File "build/bdist.linux-x86_64/egg/hggit/git_handler.py", line 187, in export_git_objects
AttributeError: 'ui' object has no attribute 'progress'

So this patch tests if ui.progress is defined and if not, it implements it and
monkey-patches the ui instance, so that everything works.

Signed-off-by: Ondrej Certik <ondrej@certik.cz>